on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: udyamwell    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd backend
        npm install

    - name: Find dependencies lock file
      run: |
        frontend_lock_file=$(find frontend -name package-lock.json)
        backend_lock_file=$(find backend -name package-lock.json)
        env frontend_lock_file=$frontend_lock_file

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dependencies
        path: |
          ${{ frontend_lock_file }}
          ${{ backend_lock_file }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: dependencies

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ steps.download-artifact.outputs.artifact-name }}
        inputs:
          deploy-to: frontend
